[package]
name = "adventofcode-2024"
authors = ["Emil Lundberg <emil@emlun.se>"]
edition = "2021"
license = "GPL-3.0-or-later"
description = "Solutions to Advent of Code 2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
print = []

[dependencies]
clap = "2.33.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
